apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: soketi
  namespace: soketi
spec:
  interval: 1m0s
  url: https://helm.soketi.app
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: soketi
  namespace: soketi
spec:
  chart:
    spec:
      chart: soketi
      sourceRef:
        kind: HelmRepository
        name: soketi
      version: 2.0.0
  interval: 10m0s
  install:
    crds: Create
  targetNamespace: soketi
  values:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
      hosts:
        - host: ws.platform.nembadminton.dk
          paths:
            - /
      tls: 
        - secretName: ws-platform-nembadminton-tls
          hosts:
            - ws.platform.nembadminton.dk

