apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../app-base/
  - nembadminton-config.yaml
  - nembadminton-secret-files-sealed.yaml
  - nembadminton-secrets-sealed.yaml
#patchesStrategicMerge:
#  - podinfo-values.yaml