kind: ConfigMap
apiVersion: v1
metadata:
  name: nembadminton-config
data:
  APP_DEBUG: "false"
  APP_ENV: production
  APP_NAME: Holdkamp
  APP_URL: https://nembadmintion.dk
  AWS_ACCESS_KEY_ID: ""
  AWS_BUCKET: ""
  AWS_DEFAULT_REGION: us-east-1
  AWS_SECRET_ACCESS_KEY: ""
  BROADCAST_DRIVER: log
  CACHE_DRIVER: database
  DB_CONNECTION: mysql
  DB_DATABASE: badminton_social_db
  DB_HOST: mysql54.unoeuro.com
  DB_PORT: "3306"
  DB_USERNAME: badminton_social
  LOG_CHANNEL: stack
  MAIL_ENCRYPTION: "null"
  MAIL_FROM_ADDRESS: "null"
  MAIL_FROM_NAME: '"${APP_NAME}"'
  MAIL_HOST: smtp.mailtrap.io
  MAIL_MAILER: smtp
  MAIL_PASSWORD: "null"
  MAIL_PORT: "2525"
  MAIL_USERNAME: "null"
  MIX_PUSHER_APP_CLUSTER: '"${PUSHER_APP_CLUSTER}"'
  MIX_PUSHER_APP_KEY: '"${PUSHER_APP_KEY}"'
  PUSHER_APP_CLUSTER: mt1
  PUSHER_APP_ID: ""
  PUSHER_APP_KEY: ""
  PUSHER_APP_SECRET: ""
  QUEUE_CONNECTION: redis
  REDIS_HOST: redis
  REDIS_PASSWORD: "null"
  REDIS_PORT: "6379"
  SESSION_DRIVER: file
  SESSION_LIFETIME: "120"
  TELESCOPE_ENABLED: "false"
  PASSPORT_PRIVATE_KEY: /opt/nembadminton/oauth-private.key
  PASSPORT_PUBLIC_KEY: /opt/nembadminton/oauth-public.key
  PASSPORT_CLIENT_ID: "1"