apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: nembadminton
 namespace: nembadminton
 annotations:
   cert-manager.io/cluster-issuer: letsencrypt
spec:
 tls:
  - hosts:
      - staging.nembadminton.dk
    secretName: staging-nembadminton-tls
 rules:
   - host: staging.nembadminton.dk
     http:
       paths:
         - path: /
           pathType: Prefix
           backend:
             service:
               name: nembadminton-web
               port:
                 number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nembadminton-web
  namespace: nembadminton
spec:
  selector:
    app: nembadminton
  ports:
  - port: 80
    targetPort: 80
