apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nembadminton
  name: nembadminton
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nembadminton
  template:
    metadata:
      labels:
        app: nembadminton
    spec:
      containers:
      - image: ghcr.io/dansk-badminton-tech/nembadminton:v0.1.0 # {"$imagepolicy": "nembadminton:nembadminton"}
        name: nembadminton-worker
        args: [
          "php", 
          "-d",
          "memory_limit=512M",
          "artisan",
          "-vvv",
          "queue:listen",
          "--memory",
          "512",
          "--timeout",
          "1800"
        ]
        envFrom:
          - configMapRef:
              name: nembadminton-config
          - secretRef:
              name: nembadminton
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "2000m"
            memory: "2Gi"
      - image: ghcr.io/dansk-badminton-tech/nembadminton:v0.1.0 # {"$imagepolicy": "nembadminton:nembadminton"}
        name: nembadminton-web
        envFrom:
          - configMapRef:
              name: nembadminton-config
          - secretRef:
              name: nembadminton
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "2000m"
            memory: "2Gi"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: nembadminton-cron
spec:
  schedule: '@midnight'
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      name: nembadminton-cron
    spec:
      template:
        spec:
          containers:
          - image: ghcr.io/dansk-badminton-tech/nembadminton:v0.1.0 # {"$imagepolicy": "nembadminton:nembadminton"}
            name: nembadminton-cron
            args: [
              "php", 
              "artisan",
              "-vvv",
              "badmintonplayer-import:update-all-clubs"
            ]
            envFrom:
              - configMapRef:
                  name: nembadminton-config
              - secretRef:
                  name: nembadminton
            resources:
              requests:
                cpu: "100m"
                memory: "256Mi"
              limits:
                cpu: "2000m"
                memory: "2Gi"
          restartPolicy: OnFailure
