apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nembadminton-worker
  name: nembadminton-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nembadminton-worker
  template:
    metadata:
      labels:
        app: nembadminton-worker
    spec:
      containers:
      - image: ghcr.io/dansk-badminton-tech/nembadminton:v0.1.0 # {"$imagepolicy": "nembadminton:nembadminton"}
        name: nembadminton-worker
        args: [
          "php", 
          "-d",
          "memory_limit=256M",
          "artisan",
          "-vvv",
          "queue:listen",
          "--memory",
          "256",
          "--timeout",
          "900"
        ]
