apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- grafana-cloud-operator/grafana-cloud-operator.yaml
- nembadminton/nembadminton.yaml
- nembadminton/image-automation.yaml
- nembadminton/redis.yaml
